# https://dev.azure.com/spyder-ide/spyder-terminal/

jobs:

################################################################################
# macOS
################################################################################
- job: 'macOS'

  pool:
    vmImage: 'macOS-10.13'

  timeoutInMinutes: 100

  variables:
    USE_CONDA: "yes"
    CI: True
    AZURE: True
    SPYDER_DEV: True

  # Run the pipeline with multiple Python versions
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
    # Set the UsePythonVersion task to reference the matrix variable for its Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: sudo chown -R 501:20 /Users/runner/.conda
    displayName: Fix .conda permissions

  - script: sudo install -d -m 0777 /usr/local/miniconda/envs/
    displayName: Fix conda env permissions

    # Conda setup environment.
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/conda-environment?view=vsts
  - task: CondaEnvironment@0
    inputs:
      environmentName: 'test'
      packageSpecs: 'python=$(python.version)'

    # Install dependencies
  - script: |
      ./continuous_integration/azure/install.sh
    displayName: 'Install dependencies'
    continueOnError: false

    # Show Conda Build Env
  - script: |
      conda list
    displayName: 'Show build environment'
    continueOnError: true

    # Run Tests
  - script: |
      ./continuous_integration/azure/runtests.sh || ./continuous_integration/azure/runtests.sh || ./continuous_integration/azure/runtests.sh || ./continuous_integration/azure/runtests.sh
    displayName: 'Run tests'
    continueOnError: false

    # Publish test results to the Azure DevOps server
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'result.xml'
      testRunTitle: 'macOS - Python $(python.version)'
      condition: succeededOrFailed()

################################################################################
# Windows
################################################################################
- job: 'Windows'

  pool:
    vmImage: 'vs2017-win2016'

  timeoutInMinutes: 100

  variables:
    CI: True
    AZURE: True
    PYTHON: "C:\\Miniconda"
    PYWINPTY_BLOCK: 0
    SPYDER_DEV: True
    CODECOV_TOKEN: "273c981b-7851-4895-a4bb-07377c67791e"

  # Run the pipeline with multiple Python versions
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        use.conda: "yes"
      # Python37:
      #   python.version: '3.7'
      #   use.conda: "no"
    maxParallel: 4

  steps:
    # Set the UsePythonVersion task to reference the matrix variable for its Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

    # Conda setup environment.
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/conda-environment?view=vsts
  - task: CondaEnvironment@0
    inputs:
      environmentName: 'test'
      packageSpecs: 'python=$(python.version)'
      updateConda: false

    # Install dependencies
  - script: |
      continuous_integration\azure\install.bat
    displayName: 'Install dependencies'
    continueOnError: false
    # Show Conda Build Env
  - script: |
      conda list
    displayName: 'Show build environment'
    continueOnError: true
    # Setup Build
  - script: |
      python setup.py build_static
    displayName: 'Setup build'
    continueOnError: false
    # Run tests
  - script: |
      python runtests.py
    displayName: 'Run tests'
    continueOnError: false
  - script: |
      continuous_integration\azure\runcodecov.bat
    displayName: 'Run code coverage'
    continueOnError: false
    # Publish test results to the Azure DevOps server
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'result.xml'
      testRunTitle: 'Windows - Python $(python.version)'
      condition: succeededOrFailed()